spring.application.name=gameFlix

spring.datasource.url=jdbc:mysql://localhost:3306/gameflix?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=403125Sl7!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.results=TRACE